-- ============================================================================
-- load-job-market-prod.sql — wgranie realnego rynku pracy (JustJoinIT) do
-- tabeli job_market_data na PRODUKCJI (Neon, baza 'main'/neondb).
--
-- WYGENEROWANE deterministycznie przez scratchpad/gen-job-market-sql.mjs z:
--   src/lib/db/data/job-market-justjoinit.json
--   snapshot:     2026-02
--   źródło:       JustJoinIT
--   sha256(json): 11116c4f192b87152e7b78bb646fe50ab91d6614e191e26d853ad6633afbaa21
--
-- Wierszy do wstawienia: 570   (distinct career_goal: 23)
-- Kolumny INSERT: career_goal, competency_name, demand_percentage, category
-- salary_range:   POMINIĘTE → baza wstawia NULL (decyzja Darka: bez widełek).
--
-- ⚠️ CZERWONA LINIA: zmiana danych prod — sign-off Ethana (CTO), bramka v1.12.
-- DELETE jest ZAWĘŻONY do 23 ścieżek (WHERE career_goal IN (…)) — nie „goły" DELETE.
-- Operacja ATOMOWA (BEGIN…COMMIT): albo cała się uda, albo nic.
-- Brak FK przychodzących na job_market_data → zero kaskad, zero danych użytkowników.
-- Tabela czytana TYLKO do odczytu (generate-gaps, faculty/dashboard).
-- ============================================================================

BEGIN;

-- Backup bieżącego stanu w tej samej transakcji (rollback ręczny = przywrócenie z _bak).
-- DROP IF EXISTS czyni re-run idempotentnym (gdyby wcześniejsza próba zostawiła tabelę).
DROP TABLE IF EXISTS job_market_data_bak;
CREATE TABLE job_market_data_bak AS SELECT * FROM job_market_data;

-- Czyszczenie poprzedniego stanu — ZAWĘŻONE do 23 ścieżek artefaktu (bramka v1.12: nie „goły" DELETE).
DELETE FROM job_market_data WHERE career_goal IN (
  '.NET Developer',
  'AI Engineer',
  'Android Developer',
  'Backend Developer',
  'Business Analyst',
  'Cybersecurity Specialist',
  'Data Analyst',
  'Data Engineer',
  'Data Scientist',
  'DevOps Engineer',
  'Embedded / C++ Developer',
  'Engineering Manager',
  'Frontend Developer',
  'Full-Stack Developer',
  'Java Developer',
  'PHP Developer',
  'Product Owner / Manager',
  'Project Manager',
  'Python Developer',
  'QA Engineer',
  'Salesforce Developer',
  'Solution Architect',
  'UX/UI Designer'
);

-- Wstawienie 570 wierszy realnego rynku.
INSERT INTO job_market_data (career_goal, competency_name, demand_percentage, category) VALUES
  ('Cybersecurity Specialist', 'Python', 15, 'Programowanie i automatyzacja'),
  ('Cybersecurity Specialist', 'SIEM', 11, 'SIEM i Monitorowanie Zdarzeń'),
  ('Cybersecurity Specialist', 'AWS', 9, 'Cloud Security'),
  ('Cybersecurity Specialist', 'Linux', 9, 'Administracja systemami i skrypty'),
  ('Cybersecurity Specialist', 'Azure', 8, 'Cloud Security'),
  ('Cybersecurity Specialist', 'IAM', 8, 'Tożsamość i zarządzanie dostępem (IAM)'),
  ('Cybersecurity Specialist', 'CI/CD', 6, 'DevSecOps i konteneryzacja'),
  ('Cybersecurity Specialist', 'Kubernetes', 6, 'DevSecOps i konteneryzacja'),
  ('Cybersecurity Specialist', 'GCP', 5, 'Cloud Security'),
  ('Cybersecurity Specialist', 'Risk Management', 5, 'Audyt, ryzyko i zgodność (GRC)'),
  ('Cybersecurity Specialist', 'SOC', 5, 'SIEM i Monitorowanie Zdarzeń'),
  ('Cybersecurity Specialist', 'Active Directory', 4, 'Tożsamość i zarządzanie dostępem (IAM)'),
  ('Cybersecurity Specialist', 'Network', 4, 'Infrastruktura i sieci'),
  ('Cybersecurity Specialist', 'Splunk', 4, 'SIEM i Monitorowanie Zdarzeń'),
  ('Cybersecurity Specialist', 'SQL', 4, 'Bazy danych (SQL)'),
  ('Cybersecurity Specialist', 'Windows', 4, 'Administracja systemami i skrypty'),
  ('Cybersecurity Specialist', 'Bash', 3, 'Administracja systemami i skrypty'),
  ('Cybersecurity Specialist', 'DevSecOps', 3, 'DevSecOps i konteneryzacja'),
  ('Cybersecurity Specialist', 'EDR / XDR', 3, 'SIEM i Monitorowanie Zdarzeń'),
  ('Cybersecurity Specialist', 'ISO 27001', 3, 'Audyt, ryzyko i zgodność (GRC)'),
  ('Cybersecurity Specialist', 'NIST', 3, 'Audyt, ryzyko i zgodność (GRC)'),
  ('Cybersecurity Specialist', 'OWASP', 3, 'Bezpieczeństwo aplikacji (AppSec)'),
  ('Cybersecurity Specialist', 'PAM', 3, 'Tożsamość i zarządzanie dostępem (IAM)'),
  ('Cybersecurity Specialist', 'PowerShell', 3, 'Administracja systemami i skrypty'),
  ('Cybersecurity Specialist', 'TCP/IP', 3, 'Infrastruktura i sieci'),
  ('Cybersecurity Specialist', 'CrowdStrike', 2, 'SIEM i Monitorowanie Zdarzeń'),
  ('Cybersecurity Specialist', 'CyberArk', 2, 'Tożsamość i zarządzanie dostępem (IAM)'),
  ('Cybersecurity Specialist', 'DORA', 2, 'Audyt, ryzyko i zgodność (GRC)'),
  ('Cybersecurity Specialist', 'Firewall / IDS-IPS', 2, 'Infrastruktura i sieci'),
  ('Cybersecurity Specialist', 'Microsoft Defender', 2, 'SIEM i Monitorowanie Zdarzeń'),
  ('Cybersecurity Specialist', 'RODO / GDPR', 2, 'Audyt, ryzyko i zgodność (GRC)'),
  ('Cybersecurity Specialist', 'SAST', 2, 'Bezpieczeństwo aplikacji (AppSec)'),
  ('Cybersecurity Specialist', 'SOAR', 2, 'SIEM i Monitorowanie Zdarzeń'),
  ('Cybersecurity Specialist', 'DAST', 1, 'Bezpieczeństwo aplikacji (AppSec)'),
  ('Cybersecurity Specialist', 'GRC', 1, 'Audyt, ryzyko i zgodność (GRC)'),
  ('Cybersecurity Specialist', 'Incident Response', 1, 'SIEM i Monitorowanie Zdarzeń'),
  ('Cybersecurity Specialist', 'SCA', 1, 'Bezpieczeństwo aplikacji (AppSec)'),
  ('AI Engineer', 'Python', 72, 'Python i praca z danymi'),
  ('AI Engineer', 'LLM', 39, 'Aplikacje LLM i GenAI'),
  ('AI Engineer', 'AWS', 21, 'Wdrażanie modeli: chmura, kontenery i MLOps'),
  ('AI Engineer', 'RAG', 21, 'Aplikacje LLM i GenAI'),
  ('AI Engineer', 'PyTorch', 20, 'Uczenie głębokie i modele ML'),
  ('AI Engineer', 'TensorFlow', 18, 'Uczenie głębokie i modele ML'),
  ('AI Engineer', 'Docker', 17, 'Wdrażanie modeli: chmura, kontenery i MLOps'),
  ('AI Engineer', 'CI/CD', 16, 'Wdrażanie modeli: chmura, kontenery i MLOps'),
  ('AI Engineer', 'Azure', 14, 'Wdrażanie modeli: chmura, kontenery i MLOps'),
  ('AI Engineer', 'LangChain', 11, 'Aplikacje LLM i GenAI'),
  ('AI Engineer', 'API / REST', 10, 'Udostępnianie modeli jako API'),
  ('AI Engineer', 'NLP', 8, 'Uczenie głębokie i modele ML'),
  ('AI Engineer', 'GenAI', 7, 'Aplikacje LLM i GenAI'),
  ('AI Engineer', 'Kubernetes', 7, 'Wdrażanie modeli: chmura, kontenery i MLOps'),
  ('AI Engineer', 'MLOps', 7, 'Wdrażanie modeli: chmura, kontenery i MLOps'),
  ('AI Engineer', 'LangGraph', 6, 'Aplikacje LLM i GenAI'),
  ('AI Engineer', 'SQL', 6, 'Python i praca z danymi'),
  ('AI Engineer', 'GCP', 5, 'Wdrażanie modeli: chmura, kontenery i MLOps'),
  ('AI Engineer', 'Java', 5, 'Języki dodatkowe'),
  ('AI Engineer', 'TypeScript', 5, 'Języki dodatkowe'),
  ('AI Engineer', 'FastAPI', 4, 'Udostępnianie modeli jako API'),
  ('AI Engineer', 'GitHub', 4, 'Udostępnianie modeli jako API'),
  ('AI Engineer', 'Hugging Face', 4, 'Aplikacje LLM i GenAI'),
  ('AI Engineer', 'IaC', 4, 'Wdrażanie modeli: chmura, kontenery i MLOps'),
  ('AI Engineer', 'Pandas', 4, 'Python i praca z danymi'),
  ('AI Engineer', 'C++', 3, 'Języki dodatkowe'),
  ('AI Engineer', 'Go', 3, 'Języki dodatkowe'),
  ('AI Engineer', 'JavaScript', 3, 'Języki dodatkowe'),
  ('AI Engineer', 'NumPy', 3, 'Python i praca z danymi'),
  ('AI Engineer', 'React', 3, 'Języki dodatkowe'),
  ('AI Engineer', 'scikit-learn', 3, 'Uczenie głębokie i modele ML'),
  ('AI Engineer', 'Uczenie głębokie (Deep Learning)', 3, 'Uczenie głębokie i modele ML'),
  ('AI Engineer', 'MLflow', 2, 'Wdrażanie modeli: chmura, kontenery i MLOps'),
  ('Data Scientist', 'Python', 55, 'Python, SQL i praca z danymi'),
  ('Data Scientist', 'Azure', 29, 'Chmura i platformy danych'),
  ('Data Scientist', 'SQL', 28, 'Python, SQL i praca z danymi'),
  ('Data Scientist', 'Databricks', 19, 'Chmura i platformy danych'),
  ('Data Scientist', 'GCP', 19, 'Chmura i platformy danych'),
  ('Data Scientist', 'LLM', 12, 'Sztuczna inteligencja: LLM, GenAI i uczenie maszynowe'),
  ('Data Scientist', 'GenAI', 9, 'Sztuczna inteligencja: LLM, GenAI i uczenie maszynowe'),
  ('Data Scientist', 'Git', 9, 'Python, SQL i praca z danymi'),
  ('Data Scientist', 'AWS', 7, 'Chmura i platformy danych'),
  ('Data Scientist', 'CI/CD', 5, 'Wielkie zbiory danych i wdrażanie (Big Data / MLOps)'),
  ('Data Scientist', 'Pandas', 5, 'Python, SQL i praca z danymi'),
  ('Data Scientist', 'Spark', 4, 'Wielkie zbiory danych i wdrażanie (Big Data / MLOps)'),
  ('Data Scientist', 'Kafka', 3, 'Wielkie zbiory danych i wdrażanie (Big Data / MLOps)'),
  ('Data Scientist', 'Kubernetes', 3, 'Wielkie zbiory danych i wdrażanie (Big Data / MLOps)'),
  ('Data Scientist', 'MLOps', 3, 'Sztuczna inteligencja: LLM, GenAI i uczenie maszynowe'),
  ('Data Scientist', 'PySpark', 3, 'Wielkie zbiory danych i wdrażanie (Big Data / MLOps)'),
  ('Data Scientist', 'Terraform', 3, 'Wielkie zbiory danych i wdrażanie (Big Data / MLOps)'),
  ('Data Scientist', 'NLP', 2, 'Sztuczna inteligencja: LLM, GenAI i uczenie maszynowe'),
  ('Data Scientist', 'NumPy', 2, 'Python, SQL i praca z danymi'),
  ('Data Scientist', 'Snowflake', 2, 'Chmura i platformy danych'),
  ('Data Scientist', 'Statystyka (Statistics)', 2, 'Sztuczna inteligencja: LLM, GenAI i uczenie maszynowe'),
  ('Data Engineer', 'Python', 70, 'Języki przetwarzania danych (rdzeń)'),
  ('Data Engineer', 'SQL', 53, 'Języki przetwarzania danych (rdzeń)'),
  ('Data Engineer', 'Databricks', 37, 'Hurtownie i platformy danych'),
  ('Data Engineer', 'Azure', 35, 'Chmura i wdrażanie'),
  ('Data Engineer', 'Apache Spark', 33, 'Big Data i przetwarzanie rozproszone'),
  ('Data Engineer', 'ETL', 31, 'Orkiestracja i ETL'),
  ('Data Engineer', 'AWS', 30, 'Chmura i wdrażanie'),
  ('Data Engineer', 'Snowflake', 30, 'Hurtownie i platformy danych'),
  ('Data Engineer', 'Airflow', 24, 'Orkiestracja i ETL'),
  ('Data Engineer', 'PySpark', 23, 'Big Data i przetwarzanie rozproszone'),
  ('Data Engineer', 'Big Data', 17, 'Big Data i przetwarzanie rozproszone'),
  ('Data Engineer', 'Scala', 13, 'Języki przetwarzania danych (rdzeń)'),
  ('Data Engineer', 'GCP', 12, 'Chmura i wdrażanie'),
  ('Data Engineer', 'dbt', 10, 'Orkiestracja i ETL'),
  ('Data Engineer', 'Kafka', 9, 'Big Data i przetwarzanie rozproszone'),
  ('Data Engineer', 'Hadoop', 7, 'Big Data i przetwarzanie rozproszone'),
  ('Data Engineer', 'CI/CD', 6, 'Chmura i wdrażanie'),
  ('Data Engineer', 'BigQuery', 5, 'Hurtownie i platformy danych'),
  ('Data Engineer', 'Azure DevOps', 4, 'Chmura i wdrażanie'),
  ('Data Engineer', 'Delta Lake', 4, 'Hurtownie i platformy danych'),
  ('Data Engineer', 'Java', 4, 'Języki przetwarzania danych (rdzeń)'),
  ('Data Engineer', 'Oracle', 4, 'Hurtownie i platformy danych'),
  ('Data Engineer', 'Azure Data Factory', 3, 'Chmura i wdrażanie'),
  ('Data Engineer', 'Terraform', 3, 'Chmura i wdrażanie'),
  ('Data Engineer', 'Cloud Composer', 2, 'Orkiestracja i ETL'),
  ('Data Engineer', 'Dagster', 2, 'Orkiestracja i ETL'),
  ('Data Engineer', 'Hive', 2, 'Big Data i przetwarzanie rozproszone'),
  ('Data Engineer', 'Kubernetes', 2, 'Chmura i wdrażanie'),
  ('Data Analyst', 'Python', 53, 'Język i zapytania do danych (fundament)'),
  ('Data Analyst', 'SQL', 48, 'Język i zapytania do danych (fundament)'),
  ('Data Analyst', 'ETL / ELT', 24, 'ETL i hurtownie danych (przepływy)'),
  ('Data Analyst', 'Power BI', 24, 'Business Intelligence i wizualizacja'),
  ('Data Analyst', 'MS Excel', 15, 'Arkusze kalkulacyjne (Excel)'),
  ('Data Analyst', 'BigQuery', 10, 'Chmurowe platformy danych'),
  ('Data Analyst', 'Modelowanie danych (Data modeling)', 10, 'ETL i hurtownie danych (przepływy)'),
  ('Data Analyst', 'GCP', 7, 'Chmurowe platformy danych'),
  ('Data Analyst', 'Azure', 6, 'Chmurowe platformy danych'),
  ('Data Analyst', 'Wielkie zbiory danych (Big Data)', 6, 'Chmurowe platformy danych'),
  ('Data Analyst', 'Business Intelligence (BI)', 5, 'Business Intelligence i wizualizacja'),
  ('Data Analyst', 'Hurtownia danych (Data Warehousing)', 5, 'ETL i hurtownie danych (przepływy)'),
  ('Data Analyst', 'Oracle', 5, 'Bazy danych i dialekty SQL'),
  ('Data Analyst', 'Tableau', 5, 'Business Intelligence i wizualizacja'),
  ('Data Analyst', 'DAX', 4, 'Business Intelligence i wizualizacja'),
  ('Data Analyst', 'Apache Airflow', 3, 'ETL i hurtownie danych (przepływy)'),
  ('Data Analyst', 'AWS', 3, 'Chmurowe platformy danych'),
  ('Data Analyst', 'DataStage', 3, 'ETL i hurtownie danych (przepływy)'),
  ('Data Analyst', 'MS SQL Server', 3, 'Bazy danych i dialekty SQL'),
  ('Data Analyst', 'Pandas', 3, 'Język i zapytania do danych (fundament)'),
  ('Data Analyst', 'Snowflake', 3, 'Chmurowe platformy danych'),
  ('Data Analyst', 'Databricks', 2, 'Chmurowe platformy danych'),
  ('Data Analyst', 'dbt', 2, 'ETL i hurtownie danych (przepływy)'),
  ('Data Analyst', 'Google Analytics', 2, 'Narzędzia specjalistyczne'),
  ('Data Analyst', 'PL/SQL', 2, 'Bazy danych i dialekty SQL'),
  ('Data Analyst', 'PostgreSQL', 2, 'Bazy danych i dialekty SQL'),
  ('Data Analyst', 'Power Query', 2, 'Business Intelligence i wizualizacja'),
  ('Data Analyst', 'Spark', 2, 'Chmurowe platformy danych'),
  ('Data Analyst', 'Bazy relacyjne (Relational Databases)', 1, 'Bazy danych i dialekty SQL'),
  ('Data Analyst', 'Integracja danych (Data Integration)', 1, 'ETL i hurtownie danych (przepływy)'),
  ('Data Analyst', 'Looker', 1, 'Business Intelligence i wizualizacja'),
  ('Data Analyst', 'NumPy', 1, 'Język i zapytania do danych (fundament)'),
  ('Data Analyst', 'PySpark', 1, 'Chmurowe platformy danych'),
  ('Data Analyst', 'SAS', 1, 'Narzędzia specjalistyczne'),
  ('Data Analyst', 'SSIS', 1, 'ETL i hurtownie danych (przepływy)'),
  ('Data Analyst', 'T-SQL', 1, 'Bazy danych i dialekty SQL'),
  ('DevOps Engineer', 'Terraform', 54, 'Infrastruktura jako kod (IaC) — rdzeń roli'),
  ('DevOps Engineer', 'Kubernetes', 43, 'Konteneryzacja i orkiestracja'),
  ('DevOps Engineer', 'CI/CD', 40, 'CI/CD i automatyzacja wydań'),
  ('DevOps Engineer', 'Python', 32, 'Systemy operacyjne i skrypty'),
  ('DevOps Engineer', 'AWS', 29, 'Chmury'),
  ('DevOps Engineer', 'Azure', 28, 'Chmury'),
  ('DevOps Engineer', 'Docker', 27, 'Konteneryzacja i orkiestracja'),
  ('DevOps Engineer', 'Ansible', 24, 'Infrastruktura jako kod (IaC) — rdzeń roli'),
  ('DevOps Engineer', 'Linux', 21, 'Systemy operacyjne i skrypty'),
  ('DevOps Engineer', 'Bash', 20, 'Systemy operacyjne i skrypty'),
  ('DevOps Engineer', 'Azure DevOps', 17, 'CI/CD i automatyzacja wydań'),
  ('DevOps Engineer', 'GCP', 13, 'Chmury'),
  ('DevOps Engineer', 'Jenkins', 10, 'CI/CD i automatyzacja wydań'),
  ('DevOps Engineer', 'PowerShell', 10, 'Systemy operacyjne i skrypty'),
  ('DevOps Engineer', 'Grafana', 8, 'Monitoring i obserwowalność'),
  ('DevOps Engineer', 'GitHub', 7, 'CI/CD i automatyzacja wydań'),
  ('DevOps Engineer', 'GitLab', 7, 'CI/CD i automatyzacja wydań'),
  ('DevOps Engineer', 'IaC', 6, 'Infrastruktura jako kod (IaC) — rdzeń roli'),
  ('DevOps Engineer', 'Prometheus', 6, 'Monitoring i obserwowalność'),
  ('DevOps Engineer', 'Go', 4, 'Systemy operacyjne i skrypty'),
  ('DevOps Engineer', 'Helm', 4, 'Infrastruktura jako kod (IaC) — rdzeń roli'),
  ('DevOps Engineer', 'Sieci (Network)', 4, 'Sieci'),
  ('DevOps Engineer', 'VMware', 3, 'Systemy operacyjne i skrypty'),
  ('DevOps Engineer', 'Windows Server', 3, 'Systemy operacyjne i skrypty'),
  ('DevOps Engineer', 'ArgoCD', 2, 'Infrastruktura jako kod (IaC) — rdzeń roli'),
  ('DevOps Engineer', 'DNS', 2, 'Sieci'),
  ('DevOps Engineer', 'GitOps', 2, 'Infrastruktura jako kod (IaC) — rdzeń roli'),
  ('DevOps Engineer', 'TCP/IP', 2, 'Sieci'),
  ('DevOps Engineer', 'Zabbix', 2, 'Monitoring i obserwowalność'),
  ('DevOps Engineer', 'Active Directory', 1, 'Niezawodność i bezpieczeństwo (SRE / DevSecOps)'),
  ('DevOps Engineer', 'AKS', 1, 'Konteneryzacja i orkiestracja'),
  ('DevOps Engineer', 'Cisco', 1, 'Sieci'),
  ('DevOps Engineer', 'Datadog', 1, 'Monitoring i obserwowalność'),
  ('DevOps Engineer', 'DevSecOps', 1, 'Niezawodność i bezpieczeństwo (SRE / DevSecOps)'),
  ('DevOps Engineer', 'IAM', 1, 'Niezawodność i bezpieczeństwo (SRE / DevSecOps)'),
  ('DevOps Engineer', 'OpenShift', 1, 'Konteneryzacja i orkiestracja'),
  ('DevOps Engineer', 'OpenStack', 1, 'Systemy operacyjne i skrypty'),
  ('DevOps Engineer', 'Proxmox', 1, 'Systemy operacyjne i skrypty'),
  ('DevOps Engineer', 'Puppet', 1, 'Infrastruktura jako kod (IaC) — rdzeń roli'),
  ('DevOps Engineer', 'Red Hat', 1, 'Systemy operacyjne i skrypty'),
  ('DevOps Engineer', 'SRE', 1, 'Niezawodność i bezpieczeństwo (SRE / DevSecOps)'),
  ('Java Developer', 'Java', 89, 'Język i ekosystem JVM (rdzeń)'),
  ('Java Developer', 'Spring / Spring Boot', 77, 'Język i ekosystem JVM (rdzeń)'),
  ('Java Developer', 'Kafka', 33, 'Architektura usług i komunikacja'),
  ('Java Developer', 'SQL', 29, 'Bazy danych'),
  ('Java Developer', 'Docker', 27, 'Chmura i wdrażanie (DevOps backendu)'),
  ('Java Developer', 'Kubernetes', 27, 'Chmura i wdrażanie (DevOps backendu)'),
  ('Java Developer', 'REST / API', 25, 'Architektura usług i komunikacja'),
  ('Java Developer', 'Hibernate', 24, 'Język i ekosystem JVM (rdzeń)'),
  ('Java Developer', 'PostgreSQL', 23, 'Bazy danych'),
  ('Java Developer', 'Mikrousługi (Microservices)', 20, 'Architektura usług i komunikacja'),
  ('Java Developer', 'Git', 13, 'Frontend i warsztat (styk full-stack)'),
  ('Java Developer', 'Angular', 12, 'Frontend i warsztat (styk full-stack)'),
  ('Java Developer', 'AWS', 12, 'Chmura i wdrażanie (DevOps backendu)'),
  ('Java Developer', 'Oracle', 11, 'Bazy danych'),
  ('Java Developer', 'Maven', 10, 'Język i ekosystem JVM (rdzeń)'),
  ('Java Developer', 'CI/CD', 8, 'Chmura i wdrażanie (DevOps backendu)'),
  ('Java Developer', 'Jenkins', 7, 'Chmura i wdrażanie (DevOps backendu)'),
  ('Java Developer', 'JUnit', 7, 'Testy i jakość kodu'),
  ('Java Developer', 'React', 7, 'Frontend i warsztat (styk full-stack)'),
  ('Java Developer', 'GCP', 6, 'Chmura i wdrażanie (DevOps backendu)'),
  ('Java Developer', 'RabbitMQ', 6, 'Architektura usług i komunikacja'),
  ('Java Developer', 'Azure', 5, 'Chmura i wdrażanie (DevOps backendu)'),
  ('Java Developer', 'Agile', 4, 'Frontend i warsztat (styk full-stack)'),
  ('Java Developer', 'JavaScript', 4, 'Frontend i warsztat (styk full-stack)'),
  ('Java Developer', 'Kotlin', 4, 'Język i ekosystem JVM (rdzeń)'),
  ('Java Developer', 'Linux', 4, 'Chmura i wdrażanie (DevOps backendu)'),
  ('Java Developer', 'NoSQL', 4, 'Bazy danych'),
  ('Java Developer', 'JPA', 3, 'Język i ekosystem JVM (rdzeń)'),
  ('Java Developer', 'MongoDB', 3, 'Bazy danych'),
  ('Java Developer', 'SOAP', 3, 'Architektura usług i komunikacja'),
  ('Java Developer', 'Elasticsearch', 2, 'Architektura usług i komunikacja'),
  ('Java Developer', 'Groovy', 2, 'Język i ekosystem JVM (rdzeń)'),
  ('Java Developer', 'PL/SQL', 2, 'Bazy danych'),
  ('Java Developer', 'Spring Security', 2, 'Testy i jakość kodu'),
  ('.NET Developer', 'C# / .NET', 85, 'Język i platforma .NET (rdzeń)'),
  ('.NET Developer', 'CI/CD', 30, 'Chmura i wdrażanie'),
  ('.NET Developer', 'SQL', 28, 'Bazy danych'),
  ('.NET Developer', 'Azure', 25, 'Chmura i wdrażanie'),
  ('.NET Developer', 'ASP.NET', 21, 'Język i platforma .NET (rdzeń)'),
  ('.NET Developer', 'Kubernetes', 20, 'Chmura i wdrażanie'),
  ('.NET Developer', 'REST / API', 20, 'Architektura usług i komunikacja'),
  ('.NET Developer', 'Docker', 18, 'Chmura i wdrażanie'),
  ('.NET Developer', 'AWS', 16, 'Chmura i wdrażanie'),
  ('.NET Developer', 'MS SQL Server', 16, 'Bazy danych'),
  ('.NET Developer', 'React', 8, 'Frontend (styk full-stack)'),
  ('.NET Developer', 'Angular', 7, 'Frontend (styk full-stack)'),
  ('.NET Developer', 'JavaScript', 7, 'Frontend (styk full-stack)'),
  ('.NET Developer', 'Entity Framework', 5, 'Język i platforma .NET (rdzeń)'),
  ('.NET Developer', 'Kafka', 5, 'Architektura usług i komunikacja'),
  ('.NET Developer', 'RabbitMQ', 5, 'Architektura usług i komunikacja'),
  ('.NET Developer', 'Terraform', 5, 'Chmura i wdrażanie'),
  ('.NET Developer', 'Azure DevOps', 4, 'Chmura i wdrażanie'),
  ('.NET Developer', 'Agile', 3, 'Warsztat i metodyka'),
  ('.NET Developer', 'Git', 3, 'Warsztat i metodyka'),
  ('.NET Developer', 'Mikrousługi (Microservices)', 3, 'Architektura usług i komunikacja'),
  ('.NET Developer', 'NoSQL', 3, 'Bazy danych'),
  ('.NET Developer', 'PostgreSQL', 3, 'Bazy danych'),
  ('.NET Developer', 'TypeScript', 3, 'Frontend (styk full-stack)'),
  ('Backend Developer', 'Python', 38, 'Języki backendu'),
  ('Backend Developer', 'AWS', 32, 'Chmura i wdrażanie (DevOps backendu)'),
  ('Backend Developer', 'Azure', 28, 'Chmura i wdrażanie (DevOps backendu)'),
  ('Backend Developer', 'Java', 27, 'Języki backendu'),
  ('Backend Developer', 'SQL', 26, 'Bazy danych'),
  ('Backend Developer', 'C# / .NET', 21, 'Języki backendu'),
  ('Backend Developer', 'Node.js', 19, 'Frameworki i środowiska uruchomieniowe'),
  ('Backend Developer', 'TypeScript', 19, 'Języki backendu'),
  ('Backend Developer', 'PostgreSQL', 16, 'Bazy danych'),
  ('Backend Developer', 'GCP', 10, 'Chmura i wdrażanie (DevOps backendu)'),
  ('Backend Developer', 'MongoDB', 8, 'Bazy danych'),
  ('Backend Developer', 'REST / API', 8, 'API, architektura i komunikacja usług'),
  ('Backend Developer', 'React', 7, 'Frontend (styk full-stack)'),
  ('Backend Developer', 'Django', 6, 'Frameworki i środowiska uruchomieniowe'),
  ('Backend Developer', 'Angular', 5, 'Frontend (styk full-stack)'),
  ('Backend Developer', 'MS SQL Server', 5, 'Bazy danych'),
  ('Backend Developer', 'Nest.js', 5, 'Frameworki i środowiska uruchomieniowe'),
  ('Backend Developer', 'NoSQL', 5, 'Bazy danych'),
  ('Backend Developer', 'Kafka', 4, 'API, architektura i komunikacja usług'),
  ('Backend Developer', 'Spring / Spring Boot', 4, 'Frameworki i środowiska uruchomieniowe'),
  ('Backend Developer', 'Next.js', 3, 'Frontend (styk full-stack)'),
  ('Backend Developer', 'CI/CD', 2, 'Chmura i wdrażanie (DevOps backendu)'),
  ('Backend Developer', 'GraphQL', 2, 'API, architektura i komunikacja usług'),
  ('Backend Developer', 'JavaScript', 2, 'Języki backendu'),
  ('Backend Developer', 'Jenkins', 2, 'Chmura i wdrażanie (DevOps backendu)'),
  ('Backend Developer', 'Kubernetes', 2, 'Chmura i wdrażanie (DevOps backendu)'),
  ('Backend Developer', 'Mikrousługi (Microservices)', 2, 'API, architektura i komunikacja usług'),
  ('Backend Developer', 'MySQL', 2, 'Bazy danych'),
  ('Backend Developer', 'Oracle', 2, 'Bazy danych'),
  ('Backend Developer', 'RabbitMQ', 2, 'API, architektura i komunikacja usług'),
  ('Backend Developer', 'Redis', 2, 'Bazy danych'),
  ('Backend Developer', 'Scala', 2, 'Języki backendu'),
  ('Backend Developer', 'Terraform', 2, 'Chmura i wdrażanie (DevOps backendu)'),
  ('Backend Developer', 'C++', 1, 'Języki backendu'),
  ('Backend Developer', 'DDD', 1, 'API, architektura i komunikacja usług'),
  ('Backend Developer', 'Flask', 1, 'Frameworki i środowiska uruchomieniowe'),
  ('Backend Developer', 'GitLab', 1, 'Chmura i wdrażanie (DevOps backendu)'),
  ('Backend Developer', 'Go', 1, 'Języki backendu'),
  ('Backend Developer', 'Helm', 1, 'Chmura i wdrażanie (DevOps backendu)'),
  ('Python Developer', 'Linux', 53, 'Infrastruktura'),
  ('Python Developer', 'Python', 46, 'Język i frameworki'),
  ('Python Developer', 'Docker', 31, 'Infrastruktura'),
  ('Python Developer', 'Kubernetes', 30, 'Infrastruktura'),
  ('Python Developer', 'AWS', 21, 'Infrastruktura'),
  ('Python Developer', 'Git', 18, 'Infrastruktura'),
  ('Python Developer', 'PostgreSQL', 15, 'Infrastruktura'),
  ('Python Developer', 'FastAPI', 11, 'Język i frameworki'),
  ('Python Developer', 'Django', 8, 'Język i frameworki'),
  ('Python Developer', 'Kafka', 5, 'Infrastruktura'),
  ('Python Developer', 'Flask', 4, 'Język i frameworki'),
  ('Python Developer', 'Jenkins', 3, 'CI/CD'),
  ('Python Developer', 'Redis', 1, 'Infrastruktura'),
  ('Frontend Developer', 'JavaScript', 60, 'Języki frontendu (rdzeń)'),
  ('Frontend Developer', 'TypeScript', 58, 'Języki frontendu (rdzeń)'),
  ('Frontend Developer', 'React', 55, 'Frameworki interfejsu i zarządzanie stanem'),
  ('Frontend Developer', 'HTML', 39, 'HTML i CSS (struktura i wygląd)'),
  ('Frontend Developer', 'CSS', 37, 'HTML i CSS (struktura i wygląd)'),
  ('Frontend Developer', 'Angular', 26, 'Frameworki interfejsu i zarządzanie stanem'),
  ('Frontend Developer', 'Node.js', 22, 'Node.js i komunikacja z API'),
  ('Frontend Developer', 'REST / API', 20, 'Node.js i komunikacja z API'),
  ('Frontend Developer', 'Git', 15, 'Narzędzia, budowanie i testy'),
  ('Frontend Developer', 'Next.js', 14, 'Frameworki interfejsu i zarządzanie stanem'),
  ('Frontend Developer', 'C# / .NET', 12, 'Inne języki i stacki (styk full-stack)'),
  ('Frontend Developer', 'CI/CD', 11, 'Narzędzia, budowanie i testy'),
  ('Frontend Developer', 'React Native', 6, 'Specjalizacje frontendu'),
  ('Frontend Developer', 'Redux', 6, 'Frameworki interfejsu i zarządzanie stanem'),
  ('Frontend Developer', 'Vue.js', 6, 'Frameworki interfejsu i zarządzanie stanem'),
  ('Frontend Developer', 'GraphQL', 5, 'Node.js i komunikacja z API'),
  ('Frontend Developer', 'Java', 5, 'Inne języki i stacki (styk full-stack)'),
  ('Frontend Developer', 'Python', 5, 'Inne języki i stacki (styk full-stack)'),
  ('Frontend Developer', 'PHP', 4, 'Inne języki i stacki (styk full-stack)'),
  ('Frontend Developer', 'ASP.NET Core', 3, 'Inne języki i stacki (styk full-stack)'),
  ('Frontend Developer', 'Ruby on Rails', 3, 'Inne języki i stacki (styk full-stack)'),
  ('Frontend Developer', 'RxJS', 3, 'Frameworki interfejsu i zarządzanie stanem'),
  ('Frontend Developer', 'UX/UI', 3, 'Specjalizacje frontendu'),
  ('Frontend Developer', 'Webpack', 3, 'Narzędzia, budowanie i testy'),
  ('Frontend Developer', 'WordPress', 3, 'Specjalizacje frontendu'),
  ('Frontend Developer', 'Cypress', 2, 'Narzędzia, budowanie i testy'),
  ('Frontend Developer', 'Jest', 2, 'Narzędzia, budowanie i testy'),
  ('Frontend Developer', 'Nest.js', 2, 'Node.js i komunikacja z API'),
  ('Frontend Developer', 'Playwright', 2, 'Narzędzia, budowanie i testy'),
  ('Frontend Developer', 'Sass / SCSS', 2, 'HTML i CSS (struktura i wygląd)'),
  ('Frontend Developer', 'Testy jednostkowe (Unit Testing)', 2, 'Narzędzia, budowanie i testy'),
  ('Frontend Developer', 'Bootstrap', 1, 'HTML i CSS (struktura i wygląd)'),
  ('Frontend Developer', 'Figma', 1, 'Specjalizacje frontendu'),
  ('Frontend Developer', 'Go', 1, 'Inne języki i stacki (styk full-stack)'),
  ('Frontend Developer', 'NgRx', 1, 'Frameworki interfejsu i zarządzanie stanem'),
  ('Frontend Developer', 'SEO', 1, 'Specjalizacje frontendu'),
  ('Frontend Developer', 'System zarządzania treścią (CMS)', 1, 'Specjalizacje frontendu'),
  ('Frontend Developer', 'Tailwind CSS', 1, 'HTML i CSS (struktura i wygląd)'),
  ('Full-Stack Developer', 'React', 60, 'Frontend'),
  ('Full-Stack Developer', 'TypeScript', 51, 'Frontend'),
  ('Full-Stack Developer', 'Java', 45, 'Backend i języki serwera'),
  ('Full-Stack Developer', 'Python', 36, 'Backend i języki serwera'),
  ('Full-Stack Developer', 'Angular', 33, 'Frontend'),
  ('Full-Stack Developer', 'AWS', 33, 'Chmura i wdrażanie'),
  ('Full-Stack Developer', 'JavaScript', 32, 'Frontend'),
  ('Full-Stack Developer', 'Node.js', 28, 'Backend i języki serwera'),
  ('Full-Stack Developer', 'CI/CD', 21, 'Chmura i wdrażanie'),
  ('Full-Stack Developer', 'Docker', 21, 'Chmura i wdrażanie'),
  ('Full-Stack Developer', 'SQL', 21, 'Bazy danych'),
  ('Full-Stack Developer', 'PostgreSQL', 18, 'Bazy danych'),
  ('Full-Stack Developer', 'Spring / Spring Boot', 15, 'Backend i języki serwera'),
  ('Full-Stack Developer', 'REST / API', 11, 'Architektura usług i komunikacja'),
  ('Full-Stack Developer', 'GCP', 7, 'Chmura i wdrażanie'),
  ('Full-Stack Developer', 'Golang', 5, 'Backend i języki serwera'),
  ('Full-Stack Developer', 'Kubernetes', 5, 'Chmura i wdrażanie'),
  ('Full-Stack Developer', 'Mikrousługi (Microservices)', 5, 'Architektura usług i komunikacja'),
  ('Full-Stack Developer', 'Kafka', 4, 'Architektura usług i komunikacja'),
  ('Full-Stack Developer', 'Azure', 3, 'Chmura i wdrażanie'),
  ('Full-Stack Developer', 'Hibernate', 3, 'Backend i języki serwera'),
  ('Full-Stack Developer', 'Kotlin', 3, 'Backend i języki serwera'),
  ('Full-Stack Developer', 'Nest.js', 3, 'Backend i języki serwera'),
  ('Full-Stack Developer', 'NoSQL', 3, 'Bazy danych'),
  ('Full-Stack Developer', 'Oracle', 3, 'Bazy danych'),
  ('Full-Stack Developer', 'React Native', 3, 'Frontend'),
  ('Full-Stack Developer', 'Redis', 3, 'Bazy danych'),
  ('Full-Stack Developer', 'Vue.js', 3, 'Frontend'),
  ('Full-Stack Developer', 'GraphQL', 2, 'Architektura usług i komunikacja'),
  ('Full-Stack Developer', 'MySQL', 2, 'Bazy danych'),
  ('Full-Stack Developer', 'Next.js', 2, 'Frontend'),
  ('Android Developer', 'Java', 55, 'Języki Androida (rdzeń)'),
  ('Android Developer', 'Kotlin', 35, 'Języki Androida (rdzeń)'),
  ('Android Developer', 'CI/CD', 25, 'Warsztat, testy i CI/CD'),
  ('Android Developer', 'Git', 17, 'Warsztat, testy i CI/CD'),
  ('Android Developer', 'REST / API', 14, 'Komunikacja z backendem'),
  ('Android Developer', 'Android SDK', 9, 'SDK i komponenty natywne Androida'),
  ('Android Developer', 'iOS', 9, 'Wieloplatformowość i iOS (styk mobilny)'),
  ('Android Developer', 'Swift', 8, 'Wieloplatformowość i iOS (styk mobilny)'),
  ('Android Developer', 'Jetpack Compose', 6, 'SDK i komponenty natywne Androida'),
  ('Android Developer', 'MVVM', 6, 'SDK i komponenty natywne Androida'),
  ('Android Developer', 'React Native', 5, 'Wieloplatformowość i iOS (styk mobilny)'),
  ('Android Developer', 'Android Studio', 4, 'SDK i komponenty natywne Androida'),
  ('Android Developer', 'Flutter', 4, 'Wieloplatformowość i iOS (styk mobilny)'),
  ('Android Developer', 'SwiftUI', 4, 'Wieloplatformowość i iOS (styk mobilny)'),
  ('Android Developer', 'Jenkins', 3, 'Warsztat, testy i CI/CD'),
  ('Android Developer', 'Maven', 3, 'Warsztat, testy i CI/CD'),
  ('Android Developer', 'SOAP', 3, 'Komunikacja z backendem'),
  ('Android Developer', 'XCode', 3, 'Wieloplatformowość i iOS (styk mobilny)'),
  ('Android Developer', 'Appium', 2, 'Warsztat, testy i CI/CD'),
  ('Android Developer', 'Coroutines', 2, 'Języki Androida (rdzeń)'),
  ('Android Developer', 'Gradle', 2, 'SDK i komponenty natywne Androida'),
  ('Android Developer', 'GraphQL', 2, 'Komunikacja z backendem'),
  ('Android Developer', 'JSON', 2, 'Komunikacja z backendem'),
  ('Android Developer', 'Kotlin Multiplatform', 2, 'Języki Androida (rdzeń)'),
  ('Android Developer', 'XML', 2, 'SDK i komponenty natywne Androida'),
  ('QA Engineer', 'Java', 47, 'Języki programowania testera'),
  ('QA Engineer', 'JavaScript', 28, 'Języki programowania testera'),
  ('QA Engineer', 'Selenium', 28, 'Automatyzacja testów interfejsu'),
  ('QA Engineer', 'SQL', 27, 'Bazy danych (SQL)'),
  ('QA Engineer', 'Python', 25, 'Języki programowania testera'),
  ('QA Engineer', 'CI/CD', 23, 'CI/CD i narzędzia inżynierskie'),
  ('QA Engineer', 'Playwright', 23, 'Automatyzacja testów interfejsu'),
  ('QA Engineer', 'C# (.NET)', 19, 'Języki programowania testera'),
  ('QA Engineer', 'Testowanie API (API Testing)', 18, 'Testowanie API i usług'),
  ('QA Engineer', 'Automatyzacja testów (Automated Testing)', 17, 'Automatyzacja testów interfejsu'),
  ('QA Engineer', 'TypeScript', 17, 'Języki programowania testera'),
  ('QA Engineer', 'API / REST', 12, 'Testowanie API i usług'),
  ('QA Engineer', 'Postman', 8, 'Testowanie API i usług'),
  ('QA Engineer', 'Testy manualne (Manual Testing)', 8, 'Testy manualne i projektowanie testów'),
  ('QA Engineer', 'Cypress', 6, 'Automatyzacja testów interfejsu'),
  ('QA Engineer', 'Jira', 6, 'Metodyki i organizacja pracy'),
  ('QA Engineer', 'Agile', 4, 'Metodyki i organizacja pracy'),
  ('QA Engineer', 'Appium', 4, 'Automatyzacja testów interfejsu'),
  ('QA Engineer', 'Cucumber', 4, 'Frameworki testowe i BDD'),
  ('QA Engineer', 'Git', 3, 'CI/CD i narzędzia inżynierskie'),
  ('QA Engineer', 'Jenkins', 3, 'CI/CD i narzędzia inżynierskie'),
  ('QA Engineer', 'Oracle', 3, 'Bazy danych (SQL)'),
  ('QA Engineer', 'C++', 2, 'Języki programowania testera'),
  ('QA Engineer', 'ISTQB', 2, 'Testy manualne i projektowanie testów'),
  ('QA Engineer', 'JUnit', 2, 'Frameworki testowe i BDD'),
  ('QA Engineer', 'Projektowanie przypadków testowych (Test Cases)', 2, 'Testy manualne i projektowanie testów'),
  ('QA Engineer', 'pytest', 2, 'Frameworki testowe i BDD'),
  ('Business Analyst', 'UML', 59, 'Notacje i modelowanie (rdzeń)'),
  ('Business Analyst', 'BPMN', 50, 'Notacje i modelowanie (rdzeń)'),
  ('Business Analyst', 'SQL', 37, 'Bazy danych i zapytania'),
  ('Business Analyst', 'Jira', 30, 'Metodyka i narzędzia zespołowe'),
  ('Business Analyst', 'Business Analysis', 27, 'Analiza wymagań i dokumentacja'),
  ('Business Analyst', 'Enterprise Architect', 26, 'Notacje i modelowanie (rdzeń)'),
  ('Business Analyst', 'Confluence', 20, 'Metodyka i narzędzia zespołowe'),
  ('Business Analyst', 'REST / API', 17, 'API, integracje i architektura usług'),
  ('Business Analyst', 'Agile', 15, 'Metodyka i narzędzia zespołowe'),
  ('Business Analyst', 'Postman', 8, 'API, integracje i architektura usług'),
  ('Business Analyst', 'Analiza systemowa', 4, 'Analiza wymagań i dokumentacja'),
  ('Business Analyst', 'Scrum', 4, 'Metodyka i narzędzia zespołowe'),
  ('Business Analyst', 'SOA', 3, 'API, integracje i architektura usług'),
  ('Business Analyst', 'SOAP', 3, 'API, integracje i architektura usług'),
  ('Business Analyst', 'SoapUI', 3, 'API, integracje i architektura usług'),
  ('Business Analyst', 'Swagger', 3, 'API, integracje i architektura usług'),
  ('Business Analyst', 'ArchiMate', 2, 'Notacje i modelowanie (rdzeń)'),
  ('Business Analyst', 'ESB', 2, 'API, integracje i architektura usług'),
  ('Business Analyst', 'Microservices (Mikrousługi)', 2, 'API, integracje i architektura usług'),
  ('Business Analyst', 'MS Office', 2, 'Metodyka i narzędzia zespołowe'),
  ('Business Analyst', 'SDLC', 2, 'Analiza wymagań i dokumentacja'),
  ('Business Analyst', 'TOGAF', 2, 'API, integracje i architektura usług'),
  ('Business Analyst', 'User Stories', 2, 'Analiza wymagań i dokumentacja'),
  ('Business Analyst', 'XML', 2, 'API, integracje i architektura usług'),
  ('Business Analyst', 'CASE', 1, 'Analiza wymagań i dokumentacja'),
  ('Project Manager', 'Project Management', 38, 'Metodyki i ramy zarządzania (rdzeń)'),
  ('Project Manager', 'Agile', 36, 'Metodyki i ramy zarządzania (rdzeń)'),
  ('Project Manager', 'Jira', 34, 'Narzędzia pracy PM'),
  ('Project Manager', 'Scrum', 20, 'Metodyki i ramy zarządzania (rdzeń)'),
  ('Project Manager', 'Confluence', 18, 'Narzędzia pracy PM'),
  ('Project Manager', 'Stakeholder Management', 8, 'Zarządzanie interesariuszami i zespołem'),
  ('Project Manager', 'Coordination', 7, 'Zarządzanie interesariuszami i zespołem'),
  ('Project Manager', 'Communication', 6, 'Zarządzanie interesariuszami i zespołem'),
  ('Project Manager', 'PRINCE2', 6, 'Metodyki i ramy zarządzania (rdzeń)'),
  ('Project Manager', 'Kanban', 5, 'Metodyki i ramy zarządzania (rdzeń)'),
  ('Project Manager', 'Business Analysis', 4, 'Styk z analizą i dostarczaniem'),
  ('Project Manager', 'SAFe', 4, 'Metodyki i ramy zarządzania (rdzeń)'),
  ('Project Manager', 'Change Management', 3, 'Zarządzanie interesariuszami i zespołem'),
  ('Project Manager', 'Governance', 3, 'Zarządzanie interesariuszami i zespołem'),
  ('Project Manager', 'Microsoft Excel', 3, 'Narzędzia pracy PM'),
  ('Project Manager', 'MS Office', 3, 'Narzędzia pracy PM'),
  ('Project Manager', 'Risk Management', 3, 'Zarządzanie interesariuszami i zespołem'),
  ('Project Manager', 'MS Project', 2, 'Narzędzia pracy PM'),
  ('Project Manager', 'PMO', 2, 'Styk z analizą i dostarczaniem'),
  ('Project Manager', 'Project Execution', 2, 'Styk z analizą i dostarczaniem'),
  ('Project Manager', 'Scrum Master', 2, 'Metodyki i ramy zarządzania (rdzeń)'),
  ('Project Manager', 'Waterfall', 2, 'Metodyki i ramy zarządzania (rdzeń)'),
  ('Product Owner / Manager', 'Myślenie analityczne (Analytical Thinking)', 39, 'Produkt i przywództwo (rdzeń)'),
  ('Product Owner / Manager', 'Product Management', 35, 'Produkt i przywództwo (rdzeń)'),
  ('Product Owner / Manager', 'Agile', 23, 'Metodyki zwinne i prowadzenie projektu'),
  ('Product Owner / Manager', 'Project Management', 18, 'Metodyki zwinne i prowadzenie projektu'),
  ('Product Owner / Manager', 'Jira', 12, 'Narzędzia pracy PO'),
  ('Product Owner / Manager', 'Scrum', 12, 'Metodyki zwinne i prowadzenie projektu'),
  ('Product Owner / Manager', 'SaaS', 11, 'Domena i systemy korporacyjne'),
  ('Product Owner / Manager', 'Confluence', 6, 'Narzędzia pracy PO'),
  ('Product Owner / Manager', 'Business Analysis', 5, 'Analiza i wymagania'),
  ('Product Owner / Manager', 'SAP', 5, 'Domena i systemy korporacyjne'),
  ('Product Owner / Manager', 'ERP', 4, 'Domena i systemy korporacyjne'),
  ('Product Owner / Manager', 'CRM', 3, 'Domena i systemy korporacyjne'),
  ('Product Owner / Manager', 'ITIL', 3, 'Domena i systemy korporacyjne'),
  ('Product Owner / Manager', 'Leadership', 3, 'Produkt i przywództwo (rdzeń)'),
  ('Product Owner / Manager', 'Kanban', 2, 'Metodyki zwinne i prowadzenie projektu'),
  ('Product Owner / Manager', 'SDLC', 2, 'Analiza i wymagania'),
  ('UX/UI Designer', 'Figma', 61, 'Narzędzia projektowe'),
  ('UX/UI Designer', 'Adobe XD', 13, 'Narzędzia projektowe'),
  ('UX/UI Designer', 'WCAG', 9, 'UX'),
  ('UX/UI Designer', 'Jira', 8, 'Współpraca'),
  ('UX/UI Designer', 'Confluence', 6, 'Współpraca'),
  ('Salesforce Developer', 'Salesforce', 34, 'Platforma Salesforce (rdzeń)'),
  ('Salesforce Developer', 'REST / API', 32, 'Integracje i API'),
  ('Salesforce Developer', 'Apex', 16, 'Platforma Salesforce (rdzeń)'),
  ('Salesforce Developer', 'HTML', 11, 'Web i interfejs'),
  ('Salesforce Developer', 'CSS', 9, 'Web i interfejs'),
  ('Salesforce Developer', 'LWC (Lightning Web Components)', 8, 'Platforma Salesforce (rdzeń)'),
  ('Salesforce Developer', 'SAP', 7, 'Systemy korporacyjne i CRM'),
  ('Salesforce Developer', 'SOAP', 5, 'Integracje i API'),
  ('Salesforce Developer', 'ERP', 4, 'Systemy korporacyjne i CRM'),
  ('Salesforce Developer', 'JavaScript', 4, 'Web i interfejs'),
  ('Salesforce Developer', 'Agile', 3, 'Warsztat i metodyka'),
  ('Salesforce Developer', 'CI/CD', 3, 'Warsztat i metodyka'),
  ('Salesforce Developer', 'CRM', 3, 'Systemy korporacyjne i CRM'),
  ('Salesforce Developer', 'Jira', 3, 'Warsztat i metodyka'),
  ('Salesforce Developer', 'JSON', 3, 'Integracje i API'),
  ('Salesforce Developer', 'Postman', 3, 'Integracje i API'),
  ('Salesforce Developer', 'Sales Cloud', 3, 'Platforma Salesforce (rdzeń)'),
  ('Salesforce Developer', 'Service Cloud', 3, 'Platforma Salesforce (rdzeń)'),
  ('Salesforce Developer', 'Visualforce', 3, 'Platforma Salesforce (rdzeń)'),
  ('Salesforce Developer', 'ServiceNow', 2, 'Systemy korporacyjne i CRM'),
  ('PHP Developer', 'SQL', 41, 'Bazy danych'),
  ('PHP Developer', 'PHP', 21, 'Język i framework'),
  ('PHP Developer', 'Git', 18, 'Infra i front'),
  ('PHP Developer', 'PostgreSQL', 17, 'Bazy danych'),
  ('PHP Developer', 'Docker', 16, 'Infra i front'),
  ('PHP Developer', 'MySQL', 15, 'Bazy danych'),
  ('PHP Developer', 'Symfony', 9, 'Język i framework'),
  ('PHP Developer', 'Laravel', 5, 'Język i framework'),
  ('PHP Developer', 'React', 3, 'Infra i front'),
  ('Solution Architect', 'Architektura systemów', 46, 'Architektura i wzorce projektowe (rdzeń roli)'),
  ('Solution Architect', 'Java', 44, 'Substrat techniczny (skąd przychodzi architekt)'),
  ('Solution Architect', 'Python', 36, 'Substrat techniczny (skąd przychodzi architekt)'),
  ('Solution Architect', 'Kubernetes', 31, 'Chmura i skalowanie'),
  ('Solution Architect', 'Azure', 26, 'Chmura i skalowanie'),
  ('Solution Architect', 'Kafka', 26, 'Integracja i komunikacja systemów'),
  ('Solution Architect', 'ETL', 12, 'Substrat techniczny (skąd przychodzi architekt)'),
  ('Solution Architect', 'REST / API', 12, 'Integracja i komunikacja systemów'),
  ('Solution Architect', 'Oracle', 11, 'Integracja i komunikacja systemów'),
  ('Solution Architect', 'GCP', 10, 'Chmura i skalowanie'),
  ('Solution Architect', 'Docker', 9, 'Chmura i skalowanie'),
  ('Solution Architect', 'Event Streaming', 7, 'Architektura i wzorce projektowe (rdzeń roli)'),
  ('Solution Architect', 'WebLogic', 7, 'Integracja i komunikacja systemów'),
  ('Solution Architect', 'Enterprise Architect', 6, 'Architektura i wzorce projektowe (rdzeń roli)'),
  ('Solution Architect', 'TOGAF', 4, 'Architektura i wzorce projektowe (rdzeń roli)'),
  ('Solution Architect', 'ArchiMate', 3, 'Architektura i wzorce projektowe (rdzeń roli)'),
  ('Solution Architect', 'DDD (Domain-Driven Design)', 3, 'Architektura i wzorce projektowe (rdzeń roli)'),
  ('Solution Architect', 'ESB', 3, 'Integracja i komunikacja systemów'),
  ('Embedded / C++ Developer', 'C++', 77, 'Języki systemowe (rdzeń)'),
  ('Embedded / C++ Developer', 'Python', 42, 'Skrypty, automatyzacja i testy'),
  ('Embedded / C++ Developer', 'C', 34, 'Języki systemowe (rdzeń)'),
  ('Embedded / C++ Developer', 'Linux', 32, 'Linux niskopoziomowy i warsztat systemowy'),
  ('Embedded / C++ Developer', 'AWS', 11, 'Chmura, kontenery i CI/CD (styk IoT/edge)'),
  ('Embedded / C++ Developer', 'CI/CD', 11, 'Chmura, kontenery i CI/CD (styk IoT/edge)'),
  ('Embedded / C++ Developer', 'Embedded Systems', 9, 'Systemy wbudowane i sprzęt'),
  ('Embedded / C++ Developer', 'Kubernetes', 9, 'Chmura, kontenery i CI/CD (styk IoT/edge)'),
  ('Embedded / C++ Developer', 'GCP', 4, 'Chmura, kontenery i CI/CD (styk IoT/edge)'),
  ('Embedded / C++ Developer', 'Rust', 4, 'Języki systemowe (rdzeń)'),
  ('Embedded / C++ Developer', 'Bash', 3, 'Linux niskopoziomowy i warsztat systemowy'),
  ('Embedded / C++ Developer', 'Docker', 3, 'Chmura, kontenery i CI/CD (styk IoT/edge)'),
  ('Embedded / C++ Developer', 'administracja systemami', 2, 'Linux niskopoziomowy i warsztat systemowy'),
  ('Embedded / C++ Developer', 'CMake', 2, 'Systemy wbudowane i sprzęt'),
  ('Embedded / C++ Developer', 'DevSecOps', 2, 'Chmura, kontenery i CI/CD (styk IoT/edge)'),
  ('Embedded / C++ Developer', 'FPGA', 2, 'Systemy wbudowane i sprzęt'),
  ('Embedded / C++ Developer', 'freeRTOS', 2, 'Systemy wbudowane i sprzęt'),
  ('Embedded / C++ Developer', 'Git', 2, 'Linux niskopoziomowy i warsztat systemowy'),
  ('Embedded / C++ Developer', 'Linux Kernel', 2, 'Linux niskopoziomowy i warsztat systemowy'),
  ('Embedded / C++ Developer', 'RTOS', 2, 'Systemy wbudowane i sprzęt'),
  ('Embedded / C++ Developer', 'sieci', 2, 'Linux niskopoziomowy i warsztat systemowy'),
  ('Embedded / C++ Developer', 'VHDL', 2, 'Systemy wbudowane i sprzęt'),
  ('Engineering Manager', 'Java', 42, 'Techniczne tło'),
  ('Engineering Manager', 'Agile', 31, 'Leadership'),
  ('Engineering Manager', 'React', 29, 'Techniczne tło'),
  ('Engineering Manager', 'Kotlin', 23, 'Techniczne tło'),
  ('Engineering Manager', 'TypeScript', 17, 'Techniczne tło'),
  ('Engineering Manager', 'Scrum', 11, 'Leadership');

-- Sanity-check W TEJ SAMEJ transakcji (przed COMMIT). Jeśli liczby się nie zgadzają — ROLLBACK.
--   Oczekiwane: count = 570, distinct career_goal = 23, salary NULL = 570
SELECT
  count(*)                                          AS wierszy,
  count(DISTINCT career_goal)                       AS sciezek,
  count(*) FILTER (WHERE salary_range IS NULL)      AS salary_null
FROM job_market_data;

COMMIT;

-- Po COMMIT, jeśli wszystko OK — backup można usunąć (lub zostawić na kilka dni):
--   DROP TABLE job_market_data_bak;
