-- ============================================================================
-- load-job-market-prod.sql — wgranie realnego rynku pracy (JustJoinIT) do
-- tabeli job_market_data na PRODUKCJI (Neon, baza 'main'/neondb).
--
-- WYGENEROWANE deterministycznie przez scratchpad/gen-job-market-sql.mjs z:
--   src/lib/db/data/job-market-justjoinit.json
--   snapshot:     2026-02
--   źródło:       JustJoinIT
--   sha256(json): 35bd9ab013b437bd0903cfaa356e9e4f591c97b5f528aa3b63983017bec76b87
--
-- Wierszy do wstawienia: 240   (distinct career_goal: 23)
-- Kolumny INSERT: career_goal, competency_name, demand_percentage, category
-- salary_range:   POMINIĘTE → baza wstawia NULL (decyzja Darka: bez widełek).
--
-- ⚠️ CZERWONA LINIA: DELETE bez WHERE na danych prod — wymaga sign-offu Darka.
-- Operacja ATOMOWA (BEGIN…COMMIT): albo cała się uda, albo nic.
-- Brak FK przychodzących na job_market_data → zero kaskad, zero danych użytkowników.
-- Tabela czytana TYLKO do odczytu (generate-gaps, faculty/dashboard).
-- ============================================================================

BEGIN;

-- Backup bieżącego stanu w tej samej transakcji (rollback ręczny = przywrócenie z _bak).
-- DROP IF EXISTS czyni re-run idempotentnym (gdyby wcześniejsza próba zostawiła tabelę).
DROP TABLE IF EXISTS job_market_data_bak;
CREATE TABLE job_market_data_bak AS SELECT * FROM job_market_data;

-- Czyszczenie poprzedniego stanu job_market_data (DELETE bez WHERE — czerwona linia).
DELETE FROM job_market_data;

-- Wstawienie 240 wierszy realnego rynku.
INSERT INTO job_market_data (career_goal, competency_name, demand_percentage, category) VALUES
  ('Cybersecurity Specialist', 'Python', 15, 'Security / IT Security'),
  ('Cybersecurity Specialist', 'AWS', 10, 'Cloud'),
  ('Cybersecurity Specialist', 'Azure', 9, 'Cloud'),
  ('Cybersecurity Specialist', 'Splunk', 5, 'SIEM / SoC'),
  ('Cybersecurity Specialist', 'Active Directory', 3, 'IAM'),
  ('Cybersecurity Specialist', 'Network', 3, 'Teoria sieci i bezpieczeństwa'),
  ('Cybersecurity Specialist', 'Kali Linux', 1, 'Cybersecurity'),
  ('Cybersecurity Specialist', 'Nmap', 1, 'Security / IT Security'),
  ('Cybersecurity Specialist', 'Wireshark', 1, 'Security / IT Security'),
  ('AI Engineer', 'Python', 75, 'Konkret bazowy'),
  ('AI Engineer', 'PyTorch', 31, 'Machine Learning'),
  ('AI Engineer', 'AWS', 29, 'Konkret bazowy'),
  ('AI Engineer', 'TensorFlow', 27, 'Machine Learning'),
  ('AI Engineer', 'Docker', 19, 'Konkret bazowy'),
  ('AI Engineer', 'LangChain', 18, 'AI'),
  ('AI Engineer', 'Azure', 16, 'Konkret bazowy'),
  ('AI Engineer', 'Pandas', 6, 'Machine Learning'),
  ('AI Engineer', 'SQL', 6, 'Konkret bazowy'),
  ('AI Engineer', 'FastAPI', 5, 'LLM / RAG / GenAI'),
  ('AI Engineer', 'NumPy', 5, 'Machine Learning'),
  ('AI Engineer', 'Scikit-learn', 5, 'Machine Learning'),
  ('AI Engineer', 'Hugging Face', 4, 'AI'),
  ('AI Engineer', 'XGBoost', 2, 'Machine Learning'),
  ('AI Engineer', 'Streamlit', 1, 'LLM / RAG / GenAI'),
  ('Data Scientist', 'Python', 55, 'AI / Data Science'),
  ('Data Scientist', 'SQL', 26, 'Konkret bazowy'),
  ('Data Scientist', 'Databricks', 13, 'Konkret bazowy'),
  ('Data Scientist', 'Pandas', 4, 'Machine Learning'),
  ('Data Scientist', 'NumPy', 1, 'Machine Learning'),
  ('Data Scientist', 'PyTorch', 1, 'Machine Learning'),
  ('Data Engineer', 'Python', 70, 'Konkret bazowy'),
  ('Data Engineer', 'SQL', 50, 'Konkret bazowy'),
  ('Data Engineer', 'Databricks', 35, 'Konkret bazowy'),
  ('Data Engineer', 'Azure', 34, 'Cloud'),
  ('Data Engineer', 'AWS', 33, 'Cloud'),
  ('Data Engineer', 'Apache Spark', 28, 'Big Data / ETL'),
  ('Data Engineer', 'Snowflake', 28, 'Big Data / ETL'),
  ('Data Engineer', 'Airflow', 23, 'Big Data / ETL'),
  ('Data Engineer', 'GCP', 22, 'Cloud'),
  ('Data Engineer', 'PySpark', 22, 'Big Data / ETL'),
  ('Data Engineer', 'Kafka', 12, 'Konkret bazowy'),
  ('Data Engineer', 'dbt', 10, 'Big Data / ETL'),
  ('Data Engineer', 'BigQuery', 6, 'Big Data / ETL'),
  ('Data Engineer', 'Scala', 5, 'Konkret bazowy'),
  ('Data Engineer', 'Docker', 1, 'Konkret bazowy'),
  ('Data Analyst', 'Python', 55, 'Konkret bazowy'),
  ('Data Analyst', 'SQL', 49, 'Konkret bazowy'),
  ('Data Analyst', 'Power BI', 24, 'Wizualizacja BI'),
  ('Data Analyst', 'MS Excel', 16, 'Wizualizacja BI'),
  ('Data Analyst', 'BigQuery', 11, 'Konkret bazowy'),
  ('Data Analyst', 'Tableau', 5, 'Wizualizacja BI'),
  ('Data Analyst', 'Airflow', 3, 'ETL'),
  ('Data Analyst', 'dbt', 2, 'ETL'),
  ('DevOps Engineer', 'Terraform', 56, 'Infrastruktura jako kod'),
  ('DevOps Engineer', 'Kubernetes', 41, 'Konteneryzacja i orkiestracja'),
  ('DevOps Engineer', 'Python', 31, 'Konkret bazowy'),
  ('DevOps Engineer', 'AWS', 28, 'Cloud'),
  ('DevOps Engineer', 'Ansible', 26, 'Infrastruktura jako kod'),
  ('DevOps Engineer', 'Docker', 25, 'Konteneryzacja i orkiestracja'),
  ('DevOps Engineer', 'Azure', 22, 'Cloud'),
  ('DevOps Engineer', 'Bash', 20, 'Konkret bazowy'),
  ('DevOps Engineer', 'Linux', 19, 'Konkret bazowy'),
  ('DevOps Engineer', 'Jenkins', 10, 'CI/CD'),
  ('DevOps Engineer', 'Grafana', 8, 'Monitoring'),
  ('DevOps Engineer', 'GCP', 7, 'Cloud'),
  ('DevOps Engineer', 'Prometheus', 6, 'Monitoring'),
  ('DevOps Engineer', 'GitHub Actions', 2, 'CI/CD'),
  ('Java Developer', 'Java', 81, 'Język i framework'),
  ('Java Developer', 'Spring Boot', 48, 'Język i framework'),
  ('Java Developer', 'Spring', 45, 'Język i framework'),
  ('Java Developer', 'SQL', 31, 'Bazy danych'),
  ('Java Developer', 'Hibernate', 25, 'Język i framework'),
  ('Java Developer', 'Oracle', 25, 'Bazy danych'),
  ('Java Developer', 'Docker', 20, 'Konteneryzacja i integracja'),
  ('Java Developer', 'PostgreSQL', 20, 'Bazy danych'),
  ('Java Developer', 'Kafka', 19, 'Konteneryzacja i integracja'),
  ('Java Developer', 'Kubernetes', 19, 'Konteneryzacja i integracja'),
  ('Java Developer', 'Maven', 9, 'Język i framework'),
  ('Java Developer', 'JUnit', 7, 'Język i framework'),
  ('Java Developer', 'Jenkins', 6, 'CI/CD'),
  ('Java Developer', 'OpenAPI', 1, 'REST API / Microservices'),
  ('Java Developer', 'Swagger', 1, 'Konteneryzacja i integracja'),
  ('.NET Developer', '.Net', 61, 'Język i framework'),
  ('.NET Developer', 'C#', 59, 'Język i framework'),
  ('.NET Developer', 'SQL', 29, 'Bazy danych'),
  ('.NET Developer', 'Azure', 23, 'Konteneryzacja i chmura'),
  ('.NET Developer', 'ASP.NET', 15, 'Język i framework'),
  ('.NET Developer', 'Kubernetes', 15, 'Konteneryzacja i chmura'),
  ('.NET Developer', 'Docker', 12, 'Konteneryzacja i chmura'),
  ('.NET Developer', '.NET Core', 10, 'Język i framework'),
  ('.NET Developer', 'SQL Server', 8, 'Bazy danych'),
  ('.NET Developer', 'ASP.NET Core', 7, 'Język i framework'),
  ('.NET Developer', 'MS SQL', 6, 'Bazy danych'),
  ('.NET Developer', 'Entity Framework', 5, 'Język i framework'),
  ('.NET Developer', 'RabbitMQ', 5, 'Konteneryzacja i chmura'),
  ('Backend Developer', 'Java', 53, 'Języki'),
  ('Backend Developer', 'Python', 39, 'Języki'),
  ('Backend Developer', 'SQL', 37, 'Bazy i cache'),
  ('Backend Developer', 'AWS', 33, 'Konteneryzacja'),
  ('Backend Developer', 'Docker', 30, 'Konteneryzacja'),
  ('Backend Developer', 'Kubernetes', 30, 'Konteneryzacja'),
  ('Backend Developer', 'TypeScript', 24, 'Języki'),
  ('Backend Developer', 'PostgreSQL', 21, 'Bazy i cache'),
  ('Backend Developer', 'Node.js', 19, 'Języki'),
  ('Backend Developer', 'Kafka', 18, 'Konteneryzacja'),
  ('Backend Developer', 'MongoDB', 5, 'Bazy i cache'),
  ('Backend Developer', 'Django', 4, 'Języki'),
  ('Backend Developer', 'GraphQL', 3, 'Konteneryzacja'),
  ('Backend Developer', 'Redis', 2, 'Bazy i cache'),
  ('Backend Developer', 'Celery', 1, 'Konteneryzacja'),
  ('Python Developer', 'Python', 46, 'Język i frameworki'),
  ('Python Developer', 'Linux', 40, 'Infrastruktura'),
  ('Python Developer', 'Kubernetes', 36, 'Infrastruktura'),
  ('Python Developer', 'Docker', 31, 'Infrastruktura'),
  ('Python Developer', 'AWS', 28, 'Infrastruktura'),
  ('Python Developer', 'PostgreSQL', 20, 'Infrastruktura'),
  ('Python Developer', 'Git', 14, 'Infrastruktura'),
  ('Python Developer', 'Django', 10, 'Język i frameworki'),
  ('Python Developer', 'FastAPI', 8, 'Język i frameworki'),
  ('Python Developer', 'Kafka', 6, 'Infrastruktura'),
  ('Python Developer', 'Flask', 5, 'Język i frameworki'),
  ('Python Developer', 'Jenkins', 4, 'CI/CD'),
  ('Python Developer', 'MongoDB', 2, 'Infrastruktura'),
  ('Python Developer', 'Redis', 1, 'Infrastruktura'),
  ('Frontend Developer', 'JavaScript', 61, 'Język i framework'),
  ('Frontend Developer', 'TypeScript', 57, 'Język i framework'),
  ('Frontend Developer', 'React', 44, 'Język i framework'),
  ('Frontend Developer', 'Node.js', 28, 'Język i framework'),
  ('Frontend Developer', 'CSS', 26, 'Styling'),
  ('Frontend Developer', 'HTML', 25, 'Styling'),
  ('Frontend Developer', 'Angular', 22, 'Język i framework'),
  ('Frontend Developer', 'Next.js', 14, 'Język i framework'),
  ('Frontend Developer', 'HTML5', 10, 'Styling'),
  ('Frontend Developer', 'CSS3', 6, 'Styling'),
  ('Frontend Developer', 'Redux', 6, 'Język i framework'),
  ('Frontend Developer', 'Cypress', 2, 'Testowanie'),
  ('Frontend Developer', 'Jest', 2, 'Testowanie'),
  ('Frontend Developer', 'Playwright', 1, 'Testowanie'),
  ('Frontend Developer', 'SASS', 1, 'Styling'),
  ('Frontend Developer', 'Tailwind CSS', 1, 'Styling'),
  ('Full-Stack Developer', 'React', 58, 'Frontend'),
  ('Full-Stack Developer', 'TypeScript', 44, 'Frontend'),
  ('Full-Stack Developer', 'Java', 41, 'Backend dla fullstacka'),
  ('Full-Stack Developer', 'AWS', 29, 'Bazy i infra'),
  ('Full-Stack Developer', 'JavaScript', 29, 'Frontend'),
  ('Full-Stack Developer', 'Python', 29, 'Backend dla fullstacka'),
  ('Full-Stack Developer', 'SQL', 22, 'Bazy i infra'),
  ('Full-Stack Developer', '.Net', 21, 'Backend dla fullstacka'),
  ('Full-Stack Developer', 'Node.js', 21, 'Backend dla fullstacka'),
  ('Full-Stack Developer', 'Docker', 10, 'Bazy i infra'),
  ('Full-Stack Developer', 'Spring Boot', 9, 'Backend dla fullstacka'),
  ('Full-Stack Developer', 'MongoDB', 2, 'Backend dla fullstacka'),
  ('Full-Stack Developer', 'Next.js', 2, 'Frontend'),
  ('Full-Stack Developer', 'Tailwind CSS', 1, 'Frontend'),
  ('Android Developer', 'Java', 55, 'Natywny Android'),
  ('Android Developer', 'Kotlin', 37, 'Natywny Android'),
  ('Android Developer', 'Git', 16, 'Konkret bazowy'),
  ('Android Developer', 'Android SDK', 10, 'Natywny Android'),
  ('Android Developer', 'Swift', 9, 'iOS / hybrydowy'),
  ('Android Developer', 'Jetpack Compose', 6, 'Natywny Android'),
  ('Android Developer', 'Android Studio', 5, 'Natywny Android'),
  ('Android Developer', 'React Native', 5, 'iOS / hybrydowy'),
  ('Android Developer', 'SwiftUI', 5, 'iOS / hybrydowy'),
  ('Android Developer', 'Flutter', 4, 'iOS / hybrydowy'),
  ('QA Engineer', 'Java', 44, 'Języki'),
  ('QA Engineer', 'JavaScript', 29, 'Języki'),
  ('QA Engineer', 'SQL', 27, 'Języki'),
  ('QA Engineer', 'Selenium', 26, 'Automatyzacja'),
  ('QA Engineer', 'Playwright', 25, 'Automatyzacja'),
  ('QA Engineer', 'Python', 22, 'Języki'),
  ('QA Engineer', 'C#', 18, 'Języki'),
  ('QA Engineer', 'TypeScript', 17, 'Języki'),
  ('QA Engineer', 'Postman', 8, 'Testowanie API'),
  ('QA Engineer', 'Cypress', 6, 'Automatyzacja'),
  ('QA Engineer', 'Jira', 5, 'Zarządzanie testami'),
  ('QA Engineer', 'TestRail', 1, 'Zarządzanie testami'),
  ('Business Analyst', 'UML', 60, 'Notacje i modelowanie'),
  ('Business Analyst', 'BPMN', 51, 'Notacje i modelowanie'),
  ('Business Analyst', 'SQL', 38, 'Dane'),
  ('Business Analyst', 'Jira', 31, 'Narzędzia analityka'),
  ('Business Analyst', 'Enterprise Architect', 27, 'Notacje i modelowanie'),
  ('Business Analyst', 'Confluence', 22, 'Narzędzia analityka'),
  ('Business Analyst', 'Postman', 9, 'Narzędzia analityka'),
  ('Project Manager', 'Jira', 39, 'Narzędzia śledzenia'),
  ('Project Manager', 'Scrum', 24, 'Agile'),
  ('Project Manager', 'Confluence', 23, 'Dokumentacja'),
  ('Project Manager', 'PRINCE2', 7, 'Agile'),
  ('Project Manager', 'Kanban', 5, 'Agile'),
  ('Project Manager', 'MS Project', 2, 'Dokumentacja'),
  ('Product Owner / Manager', 'Jira', 13, 'Narzędzia produktowe'),
  ('Product Owner / Manager', 'SaaS', 13, 'Product Management'),
  ('Product Owner / Manager', 'Scrum', 13, 'Product Management'),
  ('Product Owner / Manager', 'Confluence', 7, 'Narzędzia produktowe'),
  ('Product Owner / Manager', 'Power BI', 1, 'Analiza danych produktu'),
  ('Product Owner / Manager', 'SQL', 1, 'Analiza danych produktu'),
  ('UX/UI Designer', 'Figma', 64, 'Narzędzia projektowe'),
  ('UX/UI Designer', 'Adobe XD', 14, 'Narzędzia projektowe'),
  ('UX/UI Designer', 'Jira', 10, 'Współpraca'),
  ('UX/UI Designer', 'WCAG', 10, 'UX'),
  ('UX/UI Designer', 'Confluence', 7, 'Współpraca'),
  ('Salesforce Developer', 'Salesforce', 32, 'Ekosystem Salesforce'),
  ('Salesforce Developer', 'Apex', 15, 'Ekosystem Salesforce'),
  ('Salesforce Developer', 'HTML', 10, 'Web i integracje'),
  ('Salesforce Developer', 'LWC', 9, 'Ekosystem Salesforce'),
  ('Salesforce Developer', 'CSS', 8, 'Web i integracje'),
  ('Salesforce Developer', 'SQL', 8, 'Web i integracje'),
  ('Salesforce Developer', 'Postman', 4, 'API'),
  ('Salesforce Developer', 'Aura', 2, 'Ekosystem Salesforce'),
  ('Salesforce Developer', 'Visualforce', 2, 'Ekosystem Salesforce'),
  ('PHP Developer', 'SQL', 44, 'Bazy danych'),
  ('PHP Developer', 'PHP', 22, 'Język i framework'),
  ('PHP Developer', 'Git', 21, 'Infra i front'),
  ('PHP Developer', 'PostgreSQL', 19, 'Bazy danych'),
  ('PHP Developer', 'MySQL', 17, 'Bazy danych'),
  ('PHP Developer', 'Docker', 15, 'Infra i front'),
  ('PHP Developer', 'React', 14, 'Infra i front'),
  ('PHP Developer', 'Symfony', 11, 'Język i framework'),
  ('PHP Developer', 'Laravel', 5, 'Język i framework'),
  ('Solution Architect', 'Java', 37, 'Języki'),
  ('Solution Architect', 'Kafka', 34, 'Komunikacja i integracja'),
  ('Solution Architect', 'Python', 33, 'Języki'),
  ('Solution Architect', 'Kubernetes', 22, 'Komunikacja i integracja'),
  ('Solution Architect', 'Azure', 19, 'Cloud'),
  ('Solution Architect', 'RabbitMQ', 3, 'Komunikacja i integracja'),
  ('Solution Architect', 'GCP', 2, 'Cloud'),
  ('Solution Architect', 'AWS', 1, 'Cloud'),
  ('Solution Architect', 'C4', 1, 'Projektowanie (Architecture)'),
  ('Solution Architect', 'UML', 1, 'Projektowanie (Architecture)'),
  ('Embedded / C++ Developer', 'C++', 74, 'Języki'),
  ('Embedded / C++ Developer', 'Python', 42, 'Języki'),
  ('Embedded / C++ Developer', 'C', 35, 'Języki'),
  ('Embedded / C++ Developer', 'Linux', 34, 'Systemy'),
  ('Embedded / C++ Developer', 'Java', 24, 'Języki'),
  ('Embedded / C++ Developer', 'Kotlin', 13, 'Języki'),
  ('Engineering Manager', 'Java', 32, 'Techniczne tło'),
  ('Engineering Manager', 'Agile', 24, 'Leadership'),
  ('Engineering Manager', 'React', 23, 'Techniczne tło'),
  ('Engineering Manager', 'Kotlin', 20, 'Techniczne tło'),
  ('Engineering Manager', 'TypeScript', 14, 'Techniczne tło'),
  ('Engineering Manager', 'Scrum', 8, 'Leadership');

-- Sanity-check W TEJ SAMEJ transakcji (przed COMMIT). Jeśli liczby się nie zgadzają — ROLLBACK.
--   Oczekiwane: count = 240, distinct career_goal = 23, salary NULL = 240
SELECT
  count(*)                                          AS wierszy,
  count(DISTINCT career_goal)                       AS sciezek,
  count(*) FILTER (WHERE salary_range IS NULL)      AS salary_null
FROM job_market_data;

COMMIT;

-- Po COMMIT, jeśli wszystko OK — backup można usunąć (lub zostawić na kilka dni):
--   DROP TABLE job_market_data_bak;
